version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      # - /usr/src/app/node_modules
    command: sh -c "cd react-app && npm start"
    ports:
      - "3000:3000"